export const palette = ["#f4c95d", "#5ce1e6", "#ff8a5c", "#f57ad2", "#9bff8f"];
export const defaultNodeColor = "#ffffff";

export function createInitialState() {
  return {
    nodes: [],
    messages: [],
    paused: false,
    dynamic: false,
    nextMessageId: 1,
    lastTime: 0,
    simTime: 0,
    timeScale: 1,
    ttl: 6,
    range: 110,
    effectiveRange: 110,
    useLinkBudget: false,
    linkBudgetDb: null,
    frequencyMHz: 915,
    pathLossExp: 2.0,
    nodeCount: 80,
    width: 1200,
    height: 720,
    dragNodeId: null,
    dragNewRole: null,
    dragPointer: { x: 0, y: 0 },
    lastTransmissionCount: 0,
    lastMessageId: 0,
    lastFloodElapsedMs: null,
    onAirTime: 350,
    maxRelayWait: 500,
    activeTransmissions: [],
    carrierSenseRange: 110,
    txPower: 24,
    maxTxPowerDbm: 40,
    txGain: 3,
    rxGain: 3,
    noiseFloor: -120,
    mapScale: 1,
    hoverNodeId: null,
    terrain: null,
    terrainLayer: null,
    coordinateMode: "random",
    metersPerPixel: 10,
    earthRadiusM: 6371000,
    defaultNodeHeightM: 2,
    maxNodeHeightM: 2,
    slotTimeMsec: 60,
    cwMax: 5,
    cadTimeMsec: 4,
    maxCadAttempts: 6,
    snrMinDb: -20,
    snrMaxDb: 10,
    snrJitterDb: 4,
    loraPayloadBytes: 20,
    loraSpreadingFactor: 11,
    loraBandwidthHz: 250000,
    loraCodingRate: "4/5",
    loraPreambleSymbols: 16,
    loraExplicitHeader: true,
    loraCrcEnabled: true,
    loraLowDataRateOptimize: true,
  };
}
